alias cd..="cd .."
alias cd...="cd ../.."
alias ls='ls -oh --color=auto'
alias ll='ls -l'
alias la='ls -lAh'
alias l='ls -CF'
alias lh='ls -lh'
alias lah='ls -lAh'
alias lha='ls -lAh'
alias c='\clear;source ~/.zshrc'
alias cls='clear;source ~/.zshrc | lolcat'
alias a+='shutdown now'
alias chisto='history -c'
alias gcc='gcc -Wall -Wextra -pedantic -lm'
alias gpp='g++ -Wall -Wextra -pedantic -lm'

alias tki='echo "PTDR T ES QUI !";who'
alias SOS='xrandr -x'
alias ALED='xrandr -x -o inverted'
alias SAVEME='xrandr -o normal'
alias train='while :; do sl; done'
alias vpn='sudo openvpn --config /etc/vpn/eisti.students.conf'
alias maj='sudo dnf update && sudo dnf upgrade'
alias clear='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'
